# --- 1. UPRAVENÁ KONFIGURACE PRO CACHE ---
# Pro vyřešení problémů s cache na mobilu nastavíme soubor do složky, 
# která je stabilnější, nebo použijeme Session State jako fall-back.
import streamlit as st
import math
import os
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from PIL import Image, ImageDraw, ImageFont
import io
import base64

# --- 2. ÚPRAVA SPOTIFY SETUP ---
st.set_page_config(page_title="Tinder Playlist Generator", page_icon="🎵")
st.title("🎵 Tinder Playlist Generator")

scope = "playlist-modify-private playlist-modify-public ugc-image-upload"

# Použijeme pevnou cestu pro cache v rámci pracovního adresáře
cache_path = os.path.join(os.getcwd(), ".spotify_cache")

auth_manager = SpotifyOAuth(
    client_id=st.secrets["SPOTIPY_CLIENT_ID"],
    client_secret=st.secrets["SPOTIPY_CLIENT_SECRET"],
    redirect_uri=st.secrets["SPOTIPY_REDIRECT_URI"],
    scope=scope,
    show_dialog=False, # Nastaveno na False pro rychlejší "tiché" přihlášení
    cache_path=cache_path
)

# Automatické zpracování tokenu
if "code" in st.query_params:
    auth_manager.get_access_token(st.query_params["code"])
    st.query_params.clear()
    st.rerun()

sp = spotipy.Spotify(auth_manager=auth_manager)

# Ověření tokenu
token_info = auth_manager.get_cached_token()
if not token_info:
    auth_url = auth_manager.get_authorize_url()
    st.info("Relace vypršela nebo není aktivní.")
    st.link_button("Přihlásit se ke Spotify", auth_url)
    st.stop()

# --- 3. DEFINICE TVÝCH TRACKŮ ---
track_ids = [
    "4Vqv5vr4G4OEWINosjwX2t", "2cEFHXXBfVEMUcTAaz2jVO", "75IN3CtuZwTHTnZvYM4qnJ",
    "6ghDayhHeBXAP4OOnnrFW9", "3TzLgFxVxvFXPdIdcKY81D", "0QQviRjnsuP04U9r75fANz",
    "0D1P89Vt4rdF1m2rVE7kRK", "66BfuepFzEO1t0ZmZA4lAL", "16B00iTnq08BrEPVD9MMkh",
    "6C9X0E0E2i9NQLutXRlJcF", "11qgXw005lZy5rmrpeOL3y", "3e0ZGE7Gp034iLknjQk4QW",
    "0cGjUnkLjOBqFCF8YYuoUA", "31BPE9mx2gbSXYkmM0FIAC", "6UPTAEFulqmF8SulceHgzg"
]
track_uris = [f"spotify:track:{tid}" for tid in track_ids]

# --- 4. LOGIKA VYTVOŘENÍ ---
user_text = st.text_input("Zadej název playlistu:", "Playlist Pro")

if st.button("Vytvořit playlist"):
    if user_text:
        with st.spinner("Pracuji..."):
            # A. Vytvoření playlistu
            playlist = sp.current_user_playlist_create(user_text, public=False, description="Generated by Tinder App")
            
            # B. Přidání tvých konkrétních tracků
            sp.playlist_add_items(playlist['id'], track_uris)
            
            # C. Generování obrázku (původní funkce generate_tinder_image zůstává stejná)
            # ... [zde ponech volání funkce generate_tinder_image z tvého původního kódu] ...
            
            st.success("Hotovo! Playlist byl vytvořen a obsahuje vybrané skladby.")
            st.markdown(f"### [👉 Otevřít tvůj playlist]({playlist['external_urls']['spotify']})")
    else:
        st.warning("Zadej název.")
